### ISSUE TITLE
can't install the apk？

### ISSUE THREAD

**Issue by ForrestVV** [maldroid/manifesto#5]
when I install the apk(singed), I got the error " problems occur when parsing the package". I am really interesting at this project, wish you can give a help. thx.

**Comment by maldroid** [comment]
Can you include logcat output from the installation process?

**Comment by ForrestVV** [comment]
hi, thx for your reply. i just try it again and i got the "Failure [INSTALL_FAILED_INVALID_APK]". I sign the apk with jarsigner.

**Comment by maldroid** [comment]
Can you include the logcat output of the installation process, please? Otherwise, I cannot help you :)

**Comment by ForrestVV** [comment]
Sorry for misunderstand your words, here is the logcat:

08-10 05:51:57.163: E/art(5367): Unrecognized option -XX:mainThreadStackSize=24K
08-10 05:51:57.163: W/art(5367): Ignoring unknown -Xgc option: precise
08-10 05:51:57.193: W/art(5367): Failed to find ELF magic in /system/framework/pm.odex: dey
08-10 05:51:57.233: W/art(5367): JNI RegisterNativeMethods: attempt to register 0 native methods for android.content.res.Configuration
08-10 05:51:57.233: D/AndroidRuntime(5367): Calling main entry com.android.commands.pm.Pm
08-10 05:51:57.243: W/ResourceType(27043): XML size 0x93a or headerSize 0x1c is not on an integer boundary.
08-10 05:51:57.243: W/PackageParser(27043): Unable to read AndroidManifest.xml of /data/local/tmp/demo_signed.apk
08-10 05:51:57.243: W/PackageParser(27043): java.io.FileNotFoundException: Corrupt XML binary file
08-10 05:51:57.243: W/PackageParser(27043):     at android.content.res.AssetManager.openXmlAssetNative(Native Method)
08-10 05:51:57.243: W/PackageParser(27043):     at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
08-10 05:51:57.243: W/PackageParser(27043):     at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:456)
08-10 05:51:57.243: W/PackageParser(27043):     at android.content.pm.PackageParser.parsePackageLite(PackageParser.java:780)
08-10 05:51:57.243: W/PackageParser(27043):     at com.android.defcontainer.DefaultContainerService$1.getMinimalPackageInfo(DefaultContainerService.java:175)
08-10 05:51:57.243: W/PackageParser(27043):     at com.android.internal.app.IMediaContainerService$Stub.onTransact(IMediaContainerService.java:110)
08-10 05:51:57.243: W/PackageParser(27043):     at android.os.Binder.execTransact(Binder.java:404)
08-10 05:51:57.243: W/DefContainer(27043): Failed to parse package
08-10 05:51:57.243: W/ActivityManager(861): No content provider found for permission revoke: file:///data/local/tmp/demo_signed.apk
08-10 05:51:57.313: D/AndroidRuntime(5367): Shutting down VM
